### PR TITLE
Add table with printing support

### PR DESCRIPTION
**Pull request by pszafer**
I'd like to add table component which support printing for both Firefox and Chrome.

### CODE REVIEW

**Comment by anubra266** [comment]
Hi This looks good, but I think it'll be better if instead of having a separate table that accommodates printing, we make the two previous tables printable.

**Comment by pszafer** [comment]
It's impossible to make flex layout printable as table in Chrome. CSS display `table-header-group` is not properly used for @media print. https://bugs.chromium.org/p/chromium/issues/detail?id=962435 and in most scenarios (like all I found on the Internet) it's preferred to use flex layout for responsive table design. I think it would be better to give user a choice of implementation to use.
Of course I can redesign Flex -> Table if you think it's not necessary to have Flex layout tables.

**Comment by anubra266** [comment]
ok...I understand. Thanks for this.

**Comment by anubra266** [comment]
@all-contributors please add @pszafer for code.

**Pull request merged**
